// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnytAtAd6_x4KrXj_D6EjirHoAy04uwsg',
    appId: '1:628616680980:web:48eb3a17bb933149c67901',
    messagingSenderId: '628616680980',
    projectId: 'uic-notifier-50b72',
    authDomain: 'uic-notifier-50b72.firebaseapp.com',
    storageBucket: 'uic-notifier-50b72.appspot.com',
    measurementId: 'G-YS5YC50RG8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFBZz4OC8DMVUe-30b4PR6VEJaxGjUk3s',
    appId: '1:628616680980:android:b372639978a011b1c67901',
    messagingSenderId: '628616680980',
    projectId: 'uic-notifier-50b72',
    storageBucket: 'uic-notifier-50b72.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWDaYWKpxsaTYDXc0EOn6mTwv7XJPiJbg',
    appId: '1:628616680980:ios:973123c8d7c7a680c67901',
    messagingSenderId: '628616680980',
    projectId: 'uic-notifier-50b72',
    storageBucket: 'uic-notifier-50b72.appspot.com',
    iosClientId: '628616680980-aijfvnc2ohk8d1tptkbbkvm91tempm9r.apps.googleusercontent.com',
    iosBundleId: 'com.uic.uicn.admin',
  );
}
